modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility/issues"

[[mods]]
modId="allthecompatibility"
version="2.0.1"
displayName="All The Compatibility"
itemIcon="minecraft:crafting_table"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AllTheCompatibility.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX (RexRaptor)"
description='''
This mod adds recipe compatibility between AllTheOres and other mods!'''

[[dependencies.allthecompatibility]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="alltheores"
    mandatory=true
    versionRange="[2.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"




[[dependencies.allthecompatibility]]
    modId="voluminousenergy"
    mandatory=false
    versionRange="[1.19-0.4.0.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="indreb"
    mandatory=false
    versionRange="[1.19.2-0.14.3,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="assemblylinemachines"
    mandatory=false
    versionRange="[1.19,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="create"
    mandatory=false
    versionRange="[0.4,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="plaingrinder"
    mandatory=false
    versionRange="[1.2.4,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="botania"
    mandatory=false
    versionRange="[1.19.2-5.1.4.r,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="cyclic"
    mandatory=false
    versionRange="[1.19,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="simplegrinder"
    mandatory=false
    versionRange="[1.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="energizedpower"
    mandatory=false
    versionRange="[1.19.2-2.0.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="ad_astra"
    mandatory=false
    versionRange="[1.12.7,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.allthecompatibility]]
    modId="ftbic"
    mandatory=false
    versionRange="[1900.1.7-build.221,)"
    ordering="BEFORE"
    side="BOTH"
