modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:crafting_table"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/AllTheCompatibility_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/all-the-compatibility"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This mod adds recipe compatibility between AllTheOres and other mods!'''


[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    type="required"
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="alltheores"
    mandatory=true
    type="required"
    versionRange="[3.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    type="required"
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"




[[dependencies.${mod_id}]]
    modId="voluminousenergy"
    mandatory=false
    type="optional"
    versionRange="[1.21,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="indreb"
    mandatory=false
    type="optional"
    versionRange="[1.21,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="assemblylinemachines"
    mandatory=false
    type="optional"
    versionRange="[1.21,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=false
    type="optional"
    versionRange="[0.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="plaingrinder"
    mandatory=false
    type="optional"
    versionRange="[1.2.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="botania"
    mandatory=false
    type="optional"
    versionRange="[1.21,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cyclic"
    mandatory=false
    type="optional"
    versionRange="[1.12.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simplegrinder"
    mandatory=false
    type="optional"
    versionRange="[0.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="energizedpower"
    mandatory=false
    type="optional"
    versionRange="[1.21-2.12.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ad_astra"
    mandatory=false
    type="optional"
    versionRange="[1.15.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="modern_industrialization"
    mandatory=false
    type="optional"
    versionRange="[2.2.6-alpha,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    mandatory=false
    type="optional"
    versionRange="[19.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="oritech"
    mandatory=false
    type="optional"
    versionRange="[0.13.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="allthemodium"
    mandatory=false
    type="optional"
    versionRange="[2.8.5,)"
    ordering="AFTER"
    side="BOTH"
